import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

export default function Terms() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-4xl mx-auto px-6 py-12">
        <Button
          variant="ghost"
          onClick={() => navigate(-1)}
          className="mb-6"
        >
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back
        </Button>

        <div className="space-y-8">
          <div>
            <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
            <p className="text-muted-foreground">
              Please read these terms carefully before using Sub-Notes.
            </p>
          </div>

          <div className="space-y-6 text-sm">
            <section>
              <h2 className="font-semibold text-xl mb-3">1. Acceptance of Terms</h2>
              <p className="text-muted-foreground">
                By accessing or using Sub-Notes ("Service"), which includes the desktop application, web interface, and any associated APIs, you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-xl mb-3">2. License and Usage Restrictions</h2>

              <div className="space-y-4">
                <div>
                  <h3 className="font-medium text-base mb-2">2.1 Personal Use Only</h3>
                  <p className="text-muted-foreground">
                    Sub-Notes is strictly for personal, non-commercial use only. You may not use the Service, including any transcripts, summaries, or derived content, in any product, service, or project that generates revenue, is intended for business purposes, or is otherwise commercial in nature without prior written consent.
                  </p>
                </div>

                <div>
                  <h3 className="font-medium text-base mb-2">2.2 Prohibition on Redistribution</h3>
                  <p className="text-muted-foreground">
                    You are expressly prohibited from redistributing, republishing, reselling, or sharing any transcripts, summaries, or content generated by Sub-Notes with any third party. All content accessed through the Service is for your personal use only.
                  </p>
                </div>

                <div>
                  <h3 className="font-medium text-base mb-2">2.3 Copyright and Attribution</h3>
                  <p className="text-muted-foreground">
                    All video content, transcripts, and underlying intellectual property accessed through Sub-Notes remain the exclusive property of their original creators and copyright holders. You must maintain proper attribution to the original content creators and may not claim ownership of, or remove attribution from, any content accessed through the Service.
                  </p>
                </div>

                <div>
                  <h3 className="font-medium text-base mb-2">2.4 Account Security</h3>
                  <p className="text-muted-foreground">
                    Your account credentials are for your use only. You may not share, distribute, or expose your account access to any third party. If we detect unauthorized sharing or misuse of accounts, we may revoke access without notice.
                  </p>
                </div>

                <div>
                  <h3 className="font-medium text-base mb-2">2.5 Rate Limits and Fair Use</h3>
                  <p className="text-muted-foreground">
                    The Service may have rate limits and subscription limits depending on your plan. Exceeding these limits may result in temporary or permanent suspension. Abuse of the Service, such as excessive requests, automated scraping, or any activity that disrupts the service, is prohibited.
                  </p>
                </div>

                <div>
                  <h3 className="font-medium text-base mb-2">2.6 Use of Public Content Only</h3>
                  <p className="text-muted-foreground">
                    Sub-Notes is intended solely for use with publicly accessible YouTube videos. By using this service, you agree not to attempt to access, download, extract, or analyze content from private, unlisted, age-restricted, or otherwise restricted videos. Users are responsible for ensuring that the videos they interact with through our Service are publicly available and do not infringe on any third-party privacy rights, terms of use, or copyright protections.
                  </p>
                </div>
              </div>
            </section>

            <section>
              <h2 className="font-semibold text-xl mb-3">3. Unauthorized Access</h2>
              <p className="text-muted-foreground">
                Users must access the Service exclusively through the desktop application or web interface as provided. Any attempt to access, query, or interact with the Service through unauthorized means, including direct database queries, reverse engineering, bypassing authentication mechanisms, or accessing another user's content, is strictly prohibited. Unauthorized access may result in immediate termination of access and legal action.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-xl mb-3">4. Prohibited Activities</h2>
              <p className="text-muted-foreground mb-2">You agree not to:</p>
              <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4">
                <li>Use the Service for any illegal, harmful, or unethical activities.</li>
                <li>Redistribute, republish, or commercially exploit any transcripts, summaries, or content accessed through the Service.</li>
                <li>Remove, obscure, or modify attribution to original content creators.</li>
                <li>Reverse engineer, decompile, or attempt to extract the source code of the Service.</li>
                <li>Circumvent subscription limits, rate limits, authentication mechanisms, or any security features.</li>
                <li>Use the Service to create a competing service without prior written consent.</li>
                <li>Share, sell, or otherwise distribute content generated by the Service to third parties.</li>
              </ul>
            </section>

            <section>
              <h2 className="font-semibold text-xl mb-3">5. Intellectual Property Rights</h2>
              <p className="text-muted-foreground mb-2">
                All transcripts, summaries, and content accessed through Sub-Notes are derived from copyrighted YouTube videos owned by their respective creators. Sub-Notes does not claim ownership of any underlying content.
              </p>
              <p className="text-muted-foreground mb-2">By using Sub-Notes, you acknowledge that:</p>
              <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4">
                <li>All video content remains the property of the original creators and copyright holders</li>
                <li>Transcripts and summaries are provided solely for personal reference and note-taking</li>
                <li>You have no rights to redistribute, republish, or commercially exploit any content accessed through the Service</li>
                <li>Original attribution to content creators must be maintained at all times</li>
              </ul>
            </section>

            <section>
              <h2 className="font-semibold text-xl mb-3">6. Changes to the Service and Terms</h2>
              <p className="text-muted-foreground">
                We reserve the right to modify or discontinue the Service at any time, with or without notice. We may update these Terms periodically. Continued use of the Service after changes constitutes acceptance of the updated Terms.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-xl mb-3">7. Disclaimer and Liability</h2>
              <p className="text-muted-foreground">
                The Service is provided "as is" without any warranties of any kind. We are not responsible for any damages, data loss, or disruptions caused by the use or inability to use the Service. We do not guarantee the accuracy, completeness, or availability of transcripts or summaries. We reserve the right to terminate or suspend access to the Service for violations of these Terms. You are solely responsible for ensuring your use of the Service complies with all applicable laws and third-party terms of service, including YouTube's Terms of Service.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-xl mb-3">8. Contact</h2>
              <p className="text-muted-foreground">
                For any questions regarding these Terms, please contact support via the Sub-Notes application or GitHub repository.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-xl mb-3">9. Refund Policy</h2>
              <p className="text-muted-foreground mb-2">
                By subscribing to Sub-Notes and completing a purchase, you acknowledge that you have read, understood, and agreed to our Refund Policy.
              </p>
              <p className="text-muted-foreground mb-2">The Refund Policy outlines:</p>
              <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4">
                <li>How Sub-Notes works and its limitations (e.g., unsupported video types such as private, age-restricted, geoblocked, or non-captioned videos)</li>
                <li>The conditions under which refunds may be granted</li>
                <li>The process for requesting a refund</li>
              </ul>
              <p className="text-muted-foreground mt-2">
                Refunds are only considered under the specific circumstances described in the Refund Policy. You agree that failure to generate a summary from unsupported or restricted video content does not constitute a failure of the Service. Subscription fees are non-refundable except as explicitly stated in our Refund Policy.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-xl mb-3">10. Data Privacy</h2>
              <p className="text-muted-foreground">
                Sub-Notes collects and processes personal data in accordance with our Privacy Policy. By using the Service, you consent to such processing and warrant that all data provided by you is accurate. Transcripts may be cached to improve service performance and reduce API costs. Cached transcripts are shared across users to optimize system efficiency. We do not share your personal information or individual usage patterns with third parties except as required by law.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-xl mb-3">11. Termination</h2>
              <p className="text-muted-foreground">
                We reserve the right to terminate or suspend your account and access to the Service at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties, or for any other reason. Upon termination, your right to use the Service will immediately cease. All provisions of these Terms which by their nature should survive termination shall survive, including ownership provisions, warranty disclaimers, and limitations of liability.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-xl mb-3">12. Governing Law and Jurisdiction</h2>
              <p className="text-muted-foreground">
                These Terms of Service are governed by and construed in accordance with the laws of the United States. Any dispute, controversy, or claim arising out of or in connection with the use of the Service shall be subject to the jurisdiction of the competent courts in the United States. If you are accessing the Service from outside the United States, you are responsible for compliance with all local laws. Use of the Service is not permitted in any jurisdiction that does not give effect to all provisions of these Terms, including this section.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
